//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.24 at 11:51:14 AM CST 
//


package org.apli.modelbeans.facturacion.cfdi.v32.schema;

import java.util.Date;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class Adapter1
    extends XmlAdapter<String, Date>
{


    public Date unmarshal(String value) {
        return (org.apli.modelbeans.facturacion.schema.binder.DateTimeCustomBinder.parseDateTime(value));
    }

    public String marshal(Date value) {
        return (org.apli.modelbeans.facturacion.schema.binder.DateTimeCustomBinder.printDateTime(value));
    }

}
