//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.24 at 11:51:14 AM CST 
//


package org.apli.modelbeans.facturacion.cfdi.v32.schema;

import java.io.Serializable;
import java.util.Vector;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.apli.AD.AccesoDatos;
import javax.xml.bind.annotation.XmlTransient;
import org.apli.modelbeans.Estado;
import org.apli.modelbeans.Municipio;
import org.apli.modelbeans.Ciudad;
import org.apli.modelbeans.Pais;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Tipo definido para expresar domicilios o direcciones
 * 
 * <p>Java class for t_UbicacionFiscal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_UbicacionFiscal">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="calle" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;whiteSpace value="collapse"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="noExterior">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;whiteSpace value="collapse"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="noInterior">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;whiteSpace value="collapse"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="colonia">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;whiteSpace value="collapse"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="localidad">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;whiteSpace value="collapse"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="referencia">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;whiteSpace value="collapse"/>
 *             &lt;minLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="municipio" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;whiteSpace value="collapse"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="estado" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;whiteSpace value="collapse"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="pais" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *             &lt;whiteSpace value="collapse"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="codigoPostal" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;whiteSpace value="collapse"/>
 *             &lt;length value="5"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_UbicacionFiscal")
public class TUbicacionFiscal implements Serializable{

    private final static long serialVersionUID = -6026937020915831338L;
    @XmlAttribute(name = "calle", required = true)
    protected String calle;
    @XmlAttribute(name = "noExterior")
    protected String noExterior;
    @XmlAttribute(name = "noInterior")
    protected String noInterior;
    @XmlAttribute(name = "colonia")
    protected String colonia;
    @XmlAttribute(name = "localidad")
    protected String localidad;
    @XmlAttribute(name = "referencia")
    protected String referencia;
    @XmlAttribute(name = "municipio", required = true)
    protected String municipio;
    @XmlAttribute(name = "estado", required = true)
    protected String estado;
    @XmlAttribute(name = "pais", required = true)
    protected String pais;
    @XmlAttribute(name = "codigoPostal", required = true)
    protected String codigoPostal;
    @XmlTransient
    protected AccesoDatos oAD = null;
    @XmlTransient
    public int nIdTUbicacionFiscal;
    @XmlTransient
    private Pais oPais;
    @XmlTransient
    private Estado oEdo;
    @XmlTransient
    private Municipio oMun;
    @XmlTransient
    private Ciudad oCd;
    
    public TUbicacionFiscal(){
        this.oPais=new Pais();
        this.oEdo=new Estado();
        this.oMun=new Municipio();
        this.oCd=new Ciudad();
    }
    
    public int getIdTUbicacionFiscal() {
        return nIdTUbicacionFiscal;
    }

    public void setIdTUbicacionFiscal(int nIdTUbicacion) {
        this.nIdTUbicacionFiscal = nIdTUbicacion;
    }
    public AccesoDatos getAD() {
        return oAD;
    }
    public void setAD(AccesoDatos oAD) {
        this.oAD = oAD;
    }
    /**
     * Gets the value of the calle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalle() {
        return calle;
    }

    /**
     * Sets the value of the calle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalle(String value) {
        this.calle = value;
    }

    /**
     * Gets the value of the noExterior property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoExterior() {
        return noExterior;
    }

    /**
     * Sets the value of the noExterior property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoExterior(String value) {
        this.noExterior = value;
    }

    /**
     * Gets the value of the noInterior property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoInterior() {
        return noInterior;
    }

    /**
     * Sets the value of the noInterior property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoInterior(String value) {
        this.noInterior = value;
    }

    /**
     * Gets the value of the colonia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColonia() {
        return colonia;
    }

    /**
     * Sets the value of the colonia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColonia(String value) {
        this.colonia = value;
    }

    /**
     * Gets the value of the localidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalidad() {
        return localidad;
    }

    /**
     * Sets the value of the localidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalidad(String value) {
        this.localidad = value;
    }

    /**
     * Gets the value of the referencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferencia() {
        return referencia;
    }

    /**
     * Sets the value of the referencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferencia(String value) {
        this.referencia = value;
    }

    /**
     * Gets the value of the municipio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMunicipio() {
        return municipio;
    }

    /**
     * Sets the value of the municipio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMunicipio(String value) {
        this.municipio = value;
    }

    /**
     * Gets the value of the estado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstado() {
        return estado;
    }

    /**
     * Sets the value of the estado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstado(String value) {
        this.estado = value;
    }

    /**
     * Gets the value of the pais property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPais() {
        return pais;
    }

    /**
     * Sets the value of the pais property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPais(String value) {
        this.pais = value;
    }

    /**
     * Gets the value of the codigoPostal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoPostal() {
        return codigoPostal;
    }
    public void setCodigoPostal(String cp) {
        codigoPostal=cp;
    }
     public String buscarEstado(String clave) throws Exception{
            String estado="";
            Vector rst = null;
            Vector<TUbicacionFiscal> vObj = null;
            String sQuery = "";
            int i=0;
            sQuery = "SELECT * from buscallaveedo('"+clave+"')";
            if (getAD() == null){
                setAD(new AccesoDatos());
                getAD().conectar();
            }
            rst = getAD().ejecutarConsulta(sQuery);
            getAD().desconectar();
            setAD(null);
            if (rst != null|rst.size()>0) {
                Vector vRowTemp = (Vector)rst.elementAt(i);
                estado=((String) vRowTemp.elementAt(0));
            }
            return estado;
        }
        public String buscarMunicipio(String edo,String mun) throws Exception{
            String municipio="";
            Vector rst = null;
            Vector<TUbicacionFiscal> vObj = null;
            String sQuery = "";
            int i=0;
            sQuery = "SELECT * from buscallavemunicipio('"+edo+"','"+mun+"')";
            if (getAD() == null){
                setAD(new AccesoDatos());
                getAD().conectar();
            }
            rst = getAD().ejecutarConsulta(sQuery);
            getAD().desconectar();
            setAD(null);
            if (rst != null) {
                Vector vRowTemp = (Vector)rst.elementAt(i);
                municipio=((String) vRowTemp.elementAt(0));
            }
            return municipio;
        }
        public String buscarCiudad(String edo,String mun,String loc) throws Exception{
            String cd="";
            Vector rst = null;
            Vector<TUbicacionFiscal> vObj = null;
            String sQuery = "";
            int i=0;
            sQuery = "SELECT * from buscallaveciudad('"+edo+"','"+mun+"','"+loc+"')";
            if (getAD() == null){
                setAD(new AccesoDatos());
                getAD().conectar();
            }
            rst = getAD().ejecutarConsulta(sQuery);
            getAD().desconectar();
            setAD(null);
            if (rst != null) {
                Vector vRowTemp = (Vector)rst.elementAt(i);
                cd=((String) vRowTemp.elementAt(0));
            }
            return cd;
        }
         public String buscarPais(String clave) throws Exception{
            String estado="";
            Vector rst = null;
            Vector<TUbicacionFiscal> vObj = null;
            String sQuery = "";
            int i=0;
            sQuery = "SELECT * from buscallavepais('"+clave+"')";
            if (getAD() == null){
                setAD(new AccesoDatos());
                getAD().conectar();
            }
            rst = getAD().ejecutarConsulta(sQuery);
            getAD().desconectar();
            setAD(null);
            if (rst != null|rst.size()>0) {
                Vector vRowTemp = (Vector)rst.elementAt(i);
                estado=((String) vRowTemp.elementAt(0));
            }
            return estado;
        }
    public Pais getObjPais() {
        return oPais;
    }

    public void setObjPais(Pais oPais) {
        this.oPais = oPais;
    }
    
    public Estado getEdo() {
        return oEdo;
    }

    public void setEdo(Estado oEdo) {
        this.oEdo = oEdo;
    }

    public Municipio getMun() {
        return oMun;
    }

    public void setMun(Municipio oMun) {
        this.oMun = oMun;
    }

    public Ciudad getCd() {
        return oCd;
    }

    public void setCd(Ciudad oCd) {
        this.oCd = oCd;
    }
    
}
